import { ForbiddenException, Injectable } from '@nestjs/common';
import { DataSource } from 'typeorm';
import PDFDocument from 'pdfkit';
import ExcelJS from 'exceljs';
import { ReportApprovalEntity } from '../../database/entities/report-approval.entity';

@Injectable()
export class AdminDashboardService {
  constructor(private readonly dataSource: DataSource) {}

  async overview(days = 7) {
    const [row] = await this.dataSource.query(`SELECT COUNT(*)::int AS visits, COALESCE(SUM(total_amount) FILTER (WHERE payment_status = 'PAID'), 0)::numeric AS revenue, COUNT(*) FILTER (WHERE status = 'COMPLETED')::int AS completed, COUNT(*) FILTER (WHERE status IN ('CANCELLED', 'CANCELLED_BY_PATIENT', 'CANCELLED_BY_CLINIC'))::int AS cancelled, COUNT(*) FILTER (WHERE status = 'NO_SHOW')::int AS "noShows" FROM appointments WHERE created_at >= NOW() - ($1::int * INTERVAL '1 day')`, [days]);
    const [previousRow] = await this.dataSource.query(`SELECT COUNT(*)::int AS visits, COALESCE(SUM(total_amount) FILTER (WHERE payment_status = 'PAID'), 0)::numeric AS revenue, COUNT(*) FILTER (WHERE status = 'COMPLETED')::int AS completed, COUNT(*) FILTER (WHERE status IN ('CANCELLED', 'CANCELLED_BY_PATIENT', 'CANCELLED_BY_CLINIC'))::int AS cancelled, COUNT(*) FILTER (WHERE status = 'NO_SHOW')::int AS "noShows" FROM appointments WHERE created_at >= NOW() - ($1::int * 2 * INTERVAL '1 day') AND created_at < NOW() - ($1::int * INTERVAL '1 day')`, [days]);
    const paymentRows = await this.dataSource.query(`SELECT payment_method AS method, COALESCE(SUM(total_amount) FILTER (WHERE payment_status = 'PAID'), 0)::numeric AS revenue FROM appointments WHERE created_at >= NOW() - ($1::int * INTERVAL '1 day') GROUP BY payment_method`, [days]);
    const trendRows = await this.dataSource.query(`SELECT TO_CHAR(DATE(created_at), 'YYYY-MM-DD') AS day, COUNT(*)::int AS visits, COALESCE(SUM(total_amount) FILTER (WHERE payment_status = 'PAID'), 0)::numeric AS revenue FROM appointments WHERE created_at >= NOW() - ($1::int * INTERVAL '1 day') GROUP BY DATE(created_at) ORDER BY day`, [days]);
    const doctorPerformance = await this.dataSource.query(`SELECT staff_user.full_name AS name, specialty.name AS specialty, COUNT(appointment.id)::int AS "completedCases", COALESCE(ROUND(AVG(EXTRACT(EPOCH FROM (appointment.completed_at - appointment.checked_in_at)) / 60) FILTER (WHERE appointment.completed_at IS NOT NULL AND appointment.checked_in_at IS NOT NULL)), 0)::int AS "averageMinutes", doctor.rating_average AS rating FROM doctors doctor JOIN users staff_user ON staff_user.id = doctor.user_id JOIN specialties specialty ON specialty.id = doctor.specialty_id LEFT JOIN appointments appointment ON appointment.doctor_id = doctor.id AND appointment.status = 'COMPLETED' AND appointment.created_at >= NOW() - ($1::int * INTERVAL '1 day') GROUP BY doctor.id, staff_user.full_name, specialty.name, doctor.rating_average ORDER BY "completedCases" DESC, staff_user.full_name`, [days]);
    const visits = Number(row.visits); const revenue = Number(row.revenue); const completed = Number(row.completed); const cancelled = Number(row.cancelled); const noShows = Number(row.noShows);
    const paymentBreakdown = paymentRows.filter((payment: { method?: string }) => payment.method).map((payment: { method: string; revenue: string }) => ({ method: payment.method, revenue: Number(payment.revenue), percentage: this.rate(Number(payment.revenue), revenue) }));
    const completionRate = this.rate(completed, visits); const cancellationRate = this.rate(cancelled, visits); const noShowRate = this.rate(noShows, visits);
    const previousVisits = Number(previousRow.visits); const previousRevenue = Number(previousRow.revenue); const previousCompletionRate = this.rate(Number(previousRow.completed), previousVisits); const previousCancellationRate = this.rate(Number(previousRow.cancelled), previousVisits); const previousNoShowRate = this.rate(Number(previousRow.noShows), previousVisits);
    return { visits, revenue, completionRate, cancellationRate, noShowRate, comparison: { visits: this.change(visits, previousVisits), revenue: this.change(revenue, previousRevenue), completionRate: this.delta(completionRate, previousCompletionRate), cancellationRate: this.delta(cancellationRate, previousCancellationRate), noShowRate: this.delta(noShowRate, previousNoShowRate) }, trend: trendRows.map((trend: { day: string; visits: string; revenue: string }) => ({ day: String(trend.day), visits: Number(trend.visits), revenue: Number(trend.revenue) })), paymentBreakdown, doctorPerformance };
  }

  async approval(days: number, approvedBy: string) { const approval = await this.dataSource.getRepository(ReportApprovalEntity).save(this.dataSource.getRepository(ReportApprovalEntity).create({ approvedBy, days })); return { status: 'APPROVED', approvedAt: approval.approvedAt, approvedBy, days }; }
  async exportXlsx(days: number): Promise<Buffer> { const approval = await this.requireApproval(days); const kpi = await this.overview(days); const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet('KPI van hanh'); sheet.columns = [{ header: 'Chi so', key: 'label', width: 28 }, { header: 'Gia tri', key: 'value', width: 36 }]; sheet.addRows([{ label: 'Ky bao cao (ngay)', value: days }, { label: 'Tong luot kham', value: kpi.visits }, { label: 'Tong doanh thu (VND)', value: kpi.revenue }, { label: 'Ty le hoan thanh (%)', value: kpi.completionRate }, { label: 'No-show (%)', value: kpi.noShowRate }, { label: 'Ty le huy (%)', value: kpi.cancellationRate }, { label: 'Nguoi phe duyet', value: approval.approvedBy }, { label: 'Thoi diem phe duyet', value: approval.approvedAt.toISOString() }]); sheet.getRow(1).font = { bold: true }; sheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'DDEBF7' } }; return Buffer.from(await workbook.xlsx.writeBuffer()); }
  async exportPdf(days: number): Promise<Buffer> { const approval = await this.requireApproval(days); const kpi = await this.overview(days); return new Promise(resolve => { const doc = new PDFDocument({ margin: 44 }); const chunks: Buffer[] = []; doc.on('data', chunk => chunks.push(chunk)); doc.on('end', () => resolve(Buffer.concat(chunks))); doc.fontSize(18).text('E-Healthcare | Bao cao KPI van hanh'); doc.moveDown().fontSize(11).text(`Ky bao cao: ${days} ngay gan nhat`); doc.text(`Tong luot kham: ${kpi.visits}`); doc.text(`Tong doanh thu: ${kpi.revenue.toLocaleString('vi-VN')} VND`); doc.text(`Ty le hoan thanh: ${kpi.completionRate}%`); doc.text(`No-show / Huy: ${kpi.noShowRate}% / ${kpi.cancellationRate}%`); doc.moveDown().text('XAC NHAN PHAT HANH'); doc.text(`Nguoi phe duyet: ${approval.approvedBy}`); doc.text(`Thoi diem: ${approval.approvedAt.toISOString()}`); doc.end(); }); }
  private async requireApproval(days: number): Promise<ReportApprovalEntity> { const approval = await this.dataSource.getRepository(ReportApprovalEntity).findOne({ where: { days }, order: { approvedAt: 'DESC' } }); if (!approval) throw new ForbiddenException('Bao cao phai duoc phe duyet truoc khi xuat.'); return approval; }
  private rate(value: number, total: number) { return total ? Number(((value / total) * 100).toFixed(2)) : 0; }
  private change(value: number, previous: number) { return previous ? Number((((value - previous) / previous) * 100).toFixed(2)) : null; }
  private delta(value: number, previous: number) { return Number((value - previous).toFixed(2)); }
}
