import { HttpClient, HttpParams } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
export type CatalogType = 'SPECIALTY' | 'MEDICINE' | 'SERVICE' | 'ICD10';
export interface CatalogRow { id: string; code?: string; name?: string; brandName?: string; activeIngredient?: string; strength?: string; packageUnit?: string; contraindications?: string; referencePrice?: number; listedPrice?: number; durationMinutes?: number; description?: string; category?: string; iconUrl?: string; headDoctorId?: string; isActive: boolean; }
export interface CatalogResponse { data: CatalogRow[]; pagination: { page: number; limit: number; total: number; totalPages: number }; }
export interface CatalogSummary { specialties: number; medicines: number; services: number; icd10: number; }
export interface DoctorOption { id: string; fullName: string; academicTitle: string | null; specialty: { id: string; name: string }; }
export interface SpecialtyIconUpload { url: string; }
@Injectable({ providedIn: 'root' })
export class AdminCatalogApiService { private readonly http = inject(HttpClient); private readonly baseUrl = '/api/v1/admin/catalogs'; summary() { return this.http.get<CatalogSummary>(`${this.baseUrl}/summary`); } list(type: CatalogType, search = '', page = 1, limit = 10) { return this.http.get<CatalogResponse>(`${this.baseUrl}/${type}`, { params: new HttpParams().set('search', search).set('page', page).set('limit', limit) }); } listDoctors() { return this.http.get<{ data: DoctorOption[] }>('/api/v1/doctors/search', { params: new HttpParams().set('page', '1').set('limit', '100') }); } export(type: CatalogType, format: 'csv' | 'xlsx', search = '') { return this.http.get(`${this.baseUrl}/${type}/export/${format}`, { params: new HttpParams().set('search', search), observe: 'response', responseType: 'blob' }); } create(type: CatalogType, body: Record<string, unknown>) { return this.http.post<CatalogRow>(`${this.baseUrl}/${type}`, body); } update(type: CatalogType, id: string, body: Record<string, unknown>) { return this.http.patch<CatalogRow>(`${this.baseUrl}/${type}/${id}`, body); } setVisibility(type: CatalogType, id: string, isActive: boolean) { return this.http.patch<CatalogRow>(`${this.baseUrl}/${type}/${id}/visibility`, { isActive }); } uploadSpecialtyIcon(file: File) { const body = new FormData(); body.append('file', file); return this.http.post<SpecialtyIconUpload>(`${this.baseUrl}/specialties/icon`, body); } syncIcd10() { return this.http.post<{ synchronized: number }>(`${this.baseUrl}/icd10/sync`, {}); } }
