-- Local-only data for visually testing the ADM-03 dashboard.
-- It intentionally adds new, clearly labelled records and does not modify existing data.
BEGIN;

-- Reset only records generated by this file, so the command is safe to re-run.
DELETE FROM appointments WHERE appointment_code LIKE 'ADMDEMO-%';
DELETE FROM doctor_specialties
WHERE doctor_id IN (
  SELECT d.id FROM doctors d JOIN users u ON u.id = d.user_id
  WHERE u.email LIKE 'demo.kpi.doctor%@ehealth.local'
);
DELETE FROM doctor_schedules
WHERE doctor_id IN (
  SELECT d.id FROM doctors d JOIN users u ON u.id = d.user_id
  WHERE u.email LIKE 'demo.kpi.doctor%@ehealth.local'
);
DELETE FROM doctors
WHERE user_id IN (SELECT id FROM users WHERE email LIKE 'demo.kpi.doctor%@ehealth.local');
DELETE FROM users WHERE email LIKE 'demo.kpi.%@ehealth.local';
DELETE FROM specialties WHERE description = 'Dữ liệu minh hoạ cho báo cáo KPI';

WITH new_specialties AS (
  INSERT INTO specialties (name, description, is_active)
  VALUES
    ('Tim mạch Demo', 'Dữ liệu minh hoạ cho báo cáo KPI', true),
    ('Nội tổng quát Demo', 'Dữ liệu minh hoạ cho báo cáo KPI', true),
    ('Ngoại khoa Demo', 'Dữ liệu minh hoạ cho báo cáo KPI', true)
  RETURNING id, name
),
new_doctor_users AS (
  INSERT INTO users (email, full_name, gender, date_of_birth, status)
  VALUES
    ('demo.kpi.doctor01@ehealth.local', 'PGS.TS.BS Trần Văn Tiến', 'MALE', '1974-03-12', 'ACTIVE'),
    ('demo.kpi.doctor02@ehealth.local', 'TS.BS Nguyễn Thị Lan', 'FEMALE', '1982-07-21', 'ACTIVE'),
    ('demo.kpi.doctor03@ehealth.local', 'BSCKII Lê Văn Nam', 'MALE', '1978-11-04', 'ACTIVE'),
    ('demo.kpi.doctor04@ehealth.local', 'ThS.BS Phạm Minh Khoa', 'MALE', '1985-09-18', 'ACTIVE'),
    ('demo.kpi.doctor05@ehealth.local', 'BS.CKI Hoàng Thị Thu', 'FEMALE', '1987-02-25', 'ACTIVE'),
    ('demo.kpi.doctor06@ehealth.local', 'PGS.TS.BS Võ Đình Phúc', 'MALE', '1972-05-30', 'ACTIVE')
  RETURNING id, email
),
new_doctors AS (
  INSERT INTO doctors (user_id, specialty_id, license_number, academic_title, consultation_fee, room_number, rating_average, years_experience)
  SELECT u.id, s.id,
         'CCHN-DEMO-' || u.row_no,
         'Bác sĩ', 350000, 'P' || lpad((row_number() OVER (ORDER BY u.email))::text, 3, '0'),
         4.6 + ((row_number() OVER (ORDER BY u.email))::numeric / 100), 12
  FROM (
    SELECT id, email, row_number() OVER (ORDER BY email) AS row_no
    FROM new_doctor_users
  ) u
  JOIN (
    SELECT id, row_number() OVER (ORDER BY name) AS row_no
    FROM new_specialties
  ) s ON s.row_no = ((u.row_no - 1) % 3) + 1
  RETURNING id, specialty_id
),
numbered_doctors AS (
  SELECT id, specialty_id, row_number() OVER (ORDER BY id) AS doctor_no
  FROM new_doctors
),
new_patient AS (
  INSERT INTO users (email, full_name, gender, date_of_birth, status)
  VALUES ('demo.kpi.patient@ehealth.local', 'Bệnh nhân KPI Demo', 'OTHER', '1992-01-01', 'ACTIVE')
  RETURNING id
),
new_schedules AS (
  INSERT INTO doctor_schedules (doctor_id, date, start_time, end_time, status)
  SELECT d.id, CURRENT_DATE - pattern.day_offset, '08:00', '08:30', 'BOOKED'
  FROM numbered_doctors d
  JOIN (VALUES (0, 6), (1, 4), (2, 5), (3, 6), (4, 5), (5, 6), (6, 5), (7, 5), (8, 4), (9, 5), (10, 4), (11, 5), (12, 4), (13, 5)) AS pattern(day_offset, visits)
    ON d.doctor_no <= pattern.visits
  RETURNING id, doctor_id, date
)
INSERT INTO appointments (
  appointment_code, patient_id, doctor_id, schedule_id, status, reason_for_visit,
  payment_status, payment_method, total_amount, created_at, checked_in_at,
  completed_at, cancelled_at, cancellation_reason, paid_at
)
SELECT
  'ADMDEMO-' || to_char(s.date, 'MMDD') || '-' || lpad(row_number() OVER (ORDER BY s.date, s.doctor_id)::text, 2, '0'),
  (SELECT id FROM new_patient), s.doctor_id, s.id,
  CASE
    WHEN row_number() OVER (ORDER BY s.date, s.doctor_id) % 9 = 0 THEN 'NO_SHOW'
    WHEN row_number() OVER (ORDER BY s.date, s.doctor_id) % 7 = 0 THEN 'CANCELLED_BY_PATIENT'
    ELSE 'COMPLETED'
  END,
  'Khám sức khỏe định kỳ (dữ liệu demo)',
  CASE WHEN row_number() OVER (ORDER BY s.date, s.doctor_id) % 7 = 0 THEN 'REFUNDED' ELSE 'PAID' END,
  CASE (row_number() OVER (ORDER BY s.date, s.doctor_id) % 3)
    WHEN 0 THEN 'VNPAY'
    WHEN 1 THEN 'MOMO'
    ELSE 'PAY_AT_CLINIC'
  END,
  350000 + ((row_number() OVER (ORDER BY s.date, s.doctor_id) % 4) * 50000),
  s.date + INTERVAL '08:00',
  CASE WHEN row_number() OVER (ORDER BY s.date, s.doctor_id) % 7 = 0 OR row_number() OVER (ORDER BY s.date, s.doctor_id) % 9 = 0 THEN NULL ELSE s.date + INTERVAL '08:02' END,
  CASE WHEN row_number() OVER (ORDER BY s.date, s.doctor_id) % 7 = 0 OR row_number() OVER (ORDER BY s.date, s.doctor_id) % 9 = 0 THEN NULL ELSE s.date + INTERVAL '08:20' END,
  CASE WHEN row_number() OVER (ORDER BY s.date, s.doctor_id) % 7 = 0 THEN s.date + INTERVAL '07:30' ELSE NULL END,
  CASE WHEN row_number() OVER (ORDER BY s.date, s.doctor_id) % 7 = 0 THEN 'Bệnh nhân đổi lịch' ELSE NULL END,
  CASE WHEN row_number() OVER (ORDER BY s.date, s.doctor_id) % 7 = 0 THEN NULL ELSE s.date + INTERVAL '08:00' END
FROM new_schedules s;

INSERT INTO doctor_specialties (doctor_id, specialty_id)
SELECT id, specialty_id FROM doctors WHERE license_number LIKE 'CCHN-DEMO-%';

COMMIT;
