export enum PaymentTransactionStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  TIMEOUT = 'TIMEOUT',
  SUPERSEDED = 'SUPERSEDED',
  RECONCILIATION_REQUIRED = 'RECONCILIATION_REQUIRED',
  LATE_SUCCESS = 'LATE_SUCCESS',
}
