export enum ReceptionAuditAction {
  RECEPTION_LOOKUP = 'RECEPTION_LOOKUP',
  COUNTER_PAYMENT_COLLECTED = 'COUNTER_PAYMENT_COLLECTED',
  PATIENT_CHECKED_IN = 'PATIENT_CHECKED_IN',
  WALK_IN_BOOKED = 'WALK_IN_BOOKED',
  RECEIPT_REPRINTED = 'RECEIPT_REPRINTED',
}
